spring:
  main:
    web-application-type: none

app:
  scheduling:
    shedlock:
      defaults:
        lock-at-most-for: ${SHEDLOCK_LOCK_AT_MOST_FOR}

---

spring:
  config:
    activate:
      on-profile: customer-sync-job

app:
  customer:
    sync-job:
      cadence: ${APP_CUSTOMER_SYNC_JOB_CADENCE}
      lock-at-least-for: ${APP_CUSTOMER_SYNC_JOB_LOCK_AT_LEAST_FOR}
      lock-at-most-for: ${APP_CUSTOMER_SYNC_JOB_LOCK_AT_MOST_FOR}

---

spring:
  config:
    activate:
      on-profile: order-expiration-job

app:
  order:
    expiration-job:
      cadence: ${APP_ORDER_EXPIRATION_JOB_CADENCE}
      lock-at-least-for: ${APP_ORDER_EXPIRATION_JOB_LOCK_AT_LEAST_FOR}
      lock-at-most-for: ${APP_ORDER_EXPIRATION_JOB_LOCK_AT_MOST_FOR}
